### ISSUE TITLE
Watch together

### ISSUE THREAD

**Issue by gabinfinity** [lamhoang1256/netfilm#14]
I saw you did the watch together. Can I get a demo? I would like to test it before implementing it on my site. I already have about 1000 users.

**Comment by gabinfinity** [comment]
I got this error 

![image](https://user-images.githubusercontent.com/59806981/215287910-bd6880f3-b49e-4623-a3ef-3d208143e08c.png)

**Comment by gabinfinity** [comment]
I think the feature watch together just work with computers with the same network

**Comment by gabinfinity** [comment]
i want to report some problems with watch together.

It would be nice to add a warning for those who are not logged in. Because currently if you enter a lobby logged out, there is an infinite loading screen.

Pause buttons are not synced.

If possible, it would be nice to block other people's actions in the player, even though these actions are not synchronized.


And, 
congratulations on the excellent work

**Comment by lamhoang1256** [comment]
User not logged in room problem -> I fixed

Pause button is not synchronized: do you mean that if the host click pause, other users will be stopped? -> This option I think is not good because if others are watching it is very good. But host room click pause will be boring for users

Block other people's actions in the player -> I think should not block action user's player because each person has different preferences (mute, subtitles, pause, play,...). And these actions also do not affect others I think should not be blocked. 
however, if you want to block it, you can copy the code below into style/global.scss
```
.tuby-controls-hidden .tuby-controls {
  display: none !important;
}
```

Put a time limit for the lobby to expire and be deleted -> Currently the room will automatically delete after 5 hours created, 

Option for the lobby owner to delete the lobby and ban users from the chat what if the user is viewing but the room owner deletes it? -> The feature I think is relevant and I will research and add it later.
 
I have a simple demo and doc here: https://github.com/lamhoang1256/netfilm/blob/watch-together/README.md

**Comment by gabinfinity** [comment]
another suggest: Add the option to put a password in the lobby to enter

**Comment by gabinfinity** [comment]
and bro, you r fucking awesome

**Comment by gabinfinity** [comment]
![image](https://user-images.githubusercontent.com/59806981/215303058-0954578a-2be7-48b0-880e-71ff3ed8003e.png)
same thing bro :/

**Comment by lamhoang1256** [comment]
@gabinfinity Please check rules in Firebase
Change it to something like this

![image](https://user-images.githubusercontent.com/61537853/215303308-7a65759c-274e-4ad4-8a7c-88f41715a539.png)

**Comment by gabinfinity** [comment]
Works fine now :D thanks! Is it possible to add more providers? I can send the api to you. Your frontend is the best and is super optimized

**Comment by lamhoang1256** [comment]
@gabinfinity I think you can refer to this project, I see the project uses a lot of movie sources and subtitles

https://kaguya.live
https://github.com/hoangvu12/Kaguya

**Comment by gabinfinity** [comment]
I think is more like this. Brench v3. FlixHQ and SuperStream is awesome providers like LekoLeko https://github.com/movie-web/movie-web

**Comment by Adhaaz** [comment]
> @gabinfinity I think you can refer to this project, I see the project uses a lot of movie sources and subtitles
> 
> https://kaguya.live https://github.com/hoangvu12/Kaguya

@lamhoang1256 Sir, make the Website Owner feature can add his own movie/series files to the website using Link Hosting such as Doodstream, mixdrop And such, without the intermediary of the Loklok API anymore.. However, the Loklok API remains the main reference on the Website.. Is it possible ? But video players still use React-tuby 🫢😀

**Comment by lamhoang1256** [comment]
@Adhaaz This feature is very nice but also has a lot of difficulties. Because if you add this feature, you will have to: 

- **Build about ~ 5 new pages**: add new movie,  edit movie, manage all movies, watch video with React-tuby,  search movie
- **React-tuby** only works well with videos with video file .m3u8. If you have .mp4 then you need to convert, but converting a movie video from 30 minutes ~ 1 hour is very long and difficult.
- And many other issues such as quality, movie subtitles, where to upload the thumbnail image, the uploaded video as well optimized as loklok?...

**Comment by Adhaaz** [comment]
> @Adhaaz This feature is very nice but also has a lot of difficulties. Because if you add this feature, you will have to:
> 
> * **Build about ~ 5 new pages**: add new movie,  edit movie, manage all movies, watch video with React-tuby,  search movie
> * **React-tuby** only works well with videos with video file .m3u8. If you have .mp4 then you need to convert, but converting a movie video from 30 minutes ~ 1 hour is very long and difficult.
> * And many other issues such as quality, movie subtitles, where to upload the thumbnail image, the uploaded video as well optimized as loklok?...

If u can't add that, it's okay sir 🫢

**Comment by gabinfinity** [comment]
I think the idea behind the Netfilm project is exactly to make everything automatic. I don't think it would be nice to have the option to add manual. I suggested adding more provider so that we will have more movies and series available.

**Comment by Adhaaz** [comment]
> I think the idea behind the Netfilm project is exactly to make everything automatic. I don't think it would be nice to have the option to add manual. I suggested adding more provider so that we will have more movies and series available. I sent the movie-web link which has several providers. It's open source and it would be wonderful to add the movie-web providers here to the Netfilm project.

Yeah sir, the manual is easier... but the contents of the films and series on Api Loklok are still incomplete... so how do you add other Apis besides Api Loklok, sir? Are u going to update it?

**Comment by gabinfinity** [comment]
that why im saying to add more providers.  FlixHQ and SuperStream is awesome providers like LekoLeko https://github.com/movie-web/movie-web has it and it can be integrate do netfilm project
