### ISSUE TITLE
Loklok Server Error (B0001: sign error!)

### ISSUE THREAD

**Issue by zisra** [lamhoang1256/netfilm#29]
<img width="1190" alt="Screenshot 2023-04-25 at 11 41 06 PM" src="https://user-images.githubusercontent.com/100528712/234471652-45aac2ca-ff95-41bc-8f79-a1474f2a253b.png">
<img width="275" alt="Screenshot 2023-04-25 at 11 41 41 PM" src="https://user-images.githubusercontent.com/100528712/234471734-f3daa0f5-2d45-4ecc-b394-4f119277fcad.png">

**Comment by Adhaaz** [comment]
Loklok strengthens their API using sign and AesKey, it may be difficult to use Loklok API again

**Comment by Adhaaz** [comment]
![IMG_20230428_201536](https://user-images.githubusercontent.com/75169859/235158829-6f9a0402-43df-463b-b942-d3d115e7a66a.png)

Leaked CurrentTime, sign and aesKey script code used by Loklok, I have the full code.. there are 134 lines.. I want to use it, but still haven't found the latest Loklok base Url Api, I'm still looking for it.. because Loklok uses .env to store their base Url Api

**Comment by Adhaaz** [comment]
![IMG_20230428_203631](https://user-images.githubusercontent.com/75169859/235162475-0c2775bf-05c0-45c9-b382-14de78f9152f.png)

**Comment by lamhoang1256** [comment]
Sorry but with the all lines code in the picture, it is not easy to crack Loklok

**Comment by Adhaaz** [comment]
Yeah, every request to the Loklok API will have a different sign and aesKey, so it's hard to access...

**Comment by Adhaaz** [comment]
![IMG_20230429_165804](https://user-images.githubusercontent.com/75169859/235296794-3d4028af-02ec-4857-a5f1-f97f0c937f6d.png)

For API Section Homepage, Category, Search, Banners can still be manipulated, but in the Media PreviewInfo section it is very unlikely because, each request on the API Section Media PreviewInfo is required to have a different sign and aeskey on each film title or TV Series.

**Comment by Adhaaz** [comment]
I've tried it

**Comment by lamhoang1256** [comment]
I can get the aseKey but can't get sign. You can use **t.$nuxt.$webRSAENCRY.RSAencrypt(t.$nuxt.$store.state.app.uuid)** paste to loklok console to test

![image](https://user-images.githubusercontent.com/61537853/235297472-dd7b6c48-e822-41ce-8f14-c03baeef0bb8.png)

**Comment by Nunu27** [comment]
@lamhoang1256 it use a different key, i've just tried it.

@Adhaaz you said you have the full code, would be nice to post it here so it's more clear.

**Comment by Adhaaz** [comment]
@Nunu27 Yeah, I have the full code, but the problem is that this Sign Loklok has a Secret Key, I haven't found it yet, later if I have found the Secret key used for Sign, I will share it here ... The problem is that this Loklok Sign is a combination of encryption from the Secret Key

**Comment by Adhaaz** [comment]
@Nunu27 Yeah bruh, I got the whole code, but the prob is this Sign Loklok got some Secret Key hiding somewhere, I haven't found it yet. But no worries, I'll def let you know when I've cracked it and share it here. This Loklok Sign thingy uses some combo of encryption with that Secret Key btw.

**Comment by Nunu27** [comment]
> ![IMG_20230429_165804](https://user-images.githubusercontent.com/75169859/235296794-3d4028af-02ec-4857-a5f1-f97f0c937f6d.png)
> 
> For API Section Homepage, Category, Search, Banners can still be manipulated, but in the Media PreviewInfo section it is very unlikely, because each request on the API Section Media PreviewInfo is required to have a different sign and aeskey on each film title or TV Series.

Ah, then are tou hard coding the sign, aesKey and etc in here?

**Comment by Adhaaz** [comment]
![IMG_20230501_083256](https://user-images.githubusercontent.com/75169859/235388329-c856ba25-19eb-444a-87a5-ac0d0989e146.png)

As I said above, the Homepage, Banners, Search section can be manipulated, but not the Media PreviewInfo section, because the Sign and aesKey on Media PreviewInfo use different sign and aesKey for each film or TV Series title even for 360p, 540p, 720p, and 1080p quality have different sign and aesKey, so it is difficult to retrieve data from this Media PreviewInfo...

**Comment by zisra** [comment]
Where is the scraper code located?

**Comment by Nunu27** [comment]
> ![IMG_20230501_083256](https://user-images.githubusercontent.com/75169859/235388329-c856ba25-19eb-444a-87a5-ac0d0989e146.png)
> 
> As I said above, the Homepage, Banners, Search section can be manipulated, but not the Media PreviewInfo section, because the Sign and aesKey on Media PreviewInfo use different sign and aesKey for each film or TV Series title even for 360p, 540p, 720p, and 1080p quality have different sign and aesKey, so it is difficult to retrieve data from this Media PreviewInfo...

Ah it's the result when you intercept the request that the app made? i thought you already reimplemented the code

**Comment by Adhaaz** [comment]
I'm telling it like it is, if u don't believe me, that's fine with me 😏

**Comment by Adhaaz** [comment]
![IMG_20230601_144558](https://github.com/lamhoang1256/netfilm/assets/75169859/94d7e409-968f-47bc-b499-21943f0507c5)

@Sofie99 I have found the latest Loklok api. Okay thx 👍🫢
